### ISSUE TITLE
Enable Kilonova classification

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-broker#425]
**Describe the issue**
The Kilonova module is ready (see [here](https://github.com/astrolabsoftware/fink-science/tree/master/fink_science/kilonova)) to be deployed (fink-science>=0.4.3)! 

action items:
- [x] Update the `science.py` module #426 
- [x] Update the schema in fink-client https://github.com/astrolabsoftware/fink-client/pull/78
- [x] Deploy a new filter in fink-filters & enable it in fink-broker #433 
- [x] Redirect the substream into Slack (livestream?) https://github.com/astrolabsoftware/fink-filters/pull/15
- [x] Update the HBase schema (new entry) #431 
- [x] Update the classification receipe (fink-broker & fink-science-portal) #435 
- [x] Update ...?
